@startuml
actor "Пайдаланушы" as User
actor "Операциялық жүйе" as OS

User --> (Дауыстық команда беру)
(Дауыстық команда беру) --> (Дауысты мәтінге түрлендіру)
(Дауысты мәтінге түрлендіру) --> (Команданы талдау)
(Команданы талдау) --> (Әрекетті орындау)
(Әрекетті орындау) --> OS
OS --> (Дауыстық жауап қайтару)
(Дауыстық жауап қайтару) --> User
@enduml
